### PR TITLE
feat(game) disable undo feature by using disableUndo flag

### PR DESCRIPTION
**Pull request by shashikanthgadgay**
#### Checklist

* [x] Use a separate branch in your local repo (not `master`).
* [x] Test coverage is 100% (or you have a story for why it's ok).

#738 

Please go through the changes and let us know if there are any more changes required.

### CODE REVIEW

**Comment by shashikanthgadgay0804** [comment]
@delucis  Thank you for merging.  Can you release a minor version including these changes ?

**Comment by shashikanthgadgay** [comment]
@delucis Thank you for merging. Can you release a minor version including these changes ?

**Comment by delucis** [comment]
@shashikanthgadgay I don’t manage the releases, but maybe installing directly from GitHub will work until the next minor release: `npm i nicolodavis/boardgame.io`?

**Comment by shashikanthgadgay** [comment]
Sure. That would also work until next minor release. Thanks

**Pull request merged**
