### PR TITLE
fix(api): Expose gameover metadata in rooms endpoints.

### LINKED ISSUE #665: Game over metadata is not exposed by API
This is a follow-up to #645, where the information that a game is over was stored in the associated room's metadata. However, that data is never sent to the client via the API, so it's not usable. 

This covers adding the `gameover` metadata of each room to the return value of the `/games/:name` route.

### PR DESCRIPTION
**Pull request by adngdb**
This adds the `gameover` metadata, if it exists, to both the all rooms and single room query endpoints.

Fixes #665.

#### Checklist

* [x] Use a separate branch in your local repo (not `master`).
* [x] Test coverage is 100% (or you have a story for why it's ok).

### CODE REVIEW

**Comment by adngdb** [comment]
I'm wondering about standardizing the room identifier variable to `gameID`, as that makes it confusing from an external point of view. The API has a concept of "game", which is a type of game that can be played, and of "room" which is one instance of a given game. By talking about `gameID` when listing or creating a room, it becomes confusing for users, in my opinion. So, if we're going to introduce a breaking change anyway, I'd rather push for `roomID` and use that everywhere in the Lobby / API.

Note though that maybe what we actually mean to use in this case is the concept of a "match" instead of room / game?

**Comment by nicolodavis** [comment]
I think some of the confusion stems partly from the idea of wanting to replay a game with the same set of people, which suggests some sort of room.

I like the idea of standardizing on match. It's also used in other game servers like Colyseus and Nakama. You don't need the concept of a room because you can just transport users from their existing match to the next one (which is what the current implementation does anyway).

**Comment by delucis** [comment]
Sounds good to me! Then let’s go with `matchID`. This is a slightly more extensive change as we’ll need to update the React Lobby connection class and should probably also use `nextMatchID` in the play again endpoint (instead of `nextRoomID`). Let me know if you have any questions about those, Adrian.

**Comment by adngdb** [comment]
Hey, I'm coming back to this. I want to split the work into two parts, because I think they are very different. This PR ensures the exposure of the gameover metadata (and all metadata, actually) and refactors that into a function. 

It "solves" the naming issue by simply exposing all three possible identifiers: `gameID, `roomID` and `matchID`. I think that is a fine transition until I get to the work of using `matchID` everywhere, which I intend to do later. 

What do you think about this approach?

**Comment by delucis** [comment]
Thanks Adrian! I think this is OK for the interim, but we probably shouldn’t actually release a version in this state.

@nicolodavis What do you think about the following: release v0.39.11 with the currently unreleased patches, then plan the following breaking changes for v0.40.0:

- Standardise to `matchID`, merging this PR
- Convert move signatures from `(G, ctx, ..args)` to `({ G, ctx, ...plugins }, ...args)` (#662)
- Decide on changes to the React client props (#663)

**Comment by nicolodavis** [comment]
Yes, that sounds good. I'll get out a release now.

**Comment by nicolodavis** [comment]
Just noticed the following warning when releasing:
```
(!) Circular dependency: src/plugins/main.ts -> src/plugins/plugin-
immer.ts -> src/core/reducer.ts -> src/plugins/main.ts
(!) Circular dependency: src/core/game.ts -> src/plugins/main.ts ->
 src/plugins/plugin-immer.ts -> src/core/reducer.ts -> src/core/gam
e.ts
```

Haven't had time to investigate which commit introduced this.

**Comment by adngdb** [comment]
Ah, I see the base branch is now `0.40.0`, can we thus merge this? It will be easier for to work on the follow-up if we do.

**Comment by delucis** [comment]
@adngdb Done! Thanks for your patience. We can keep working towards these breaking changes on 0.40.0 if you’d like to tackle the standardisation to `matchID`.

**Pull request merged**
