### PR TITLE
Some Improvements for Lobby  #354

### PR DESCRIPTION
**Pull request by EunPyoLee**
1. Added auto refresh functionality(refreshes every second)
2.  Show leave button even if the game is ready to play or the room is full.
#### Checklist

* [ ] Use a separate branch in your local repo (not `master`).
* [ ] Test coverage is 100% (or you have a story for why it's ok).

### CODE REVIEW

**Comment by nicolodavis** [comment]
This was already implemented in https://github.com/nicolodavis/boardgame.io/pull/510 I think.  Feel free to re-open if you are adding something else.

**Comment by EunPyoLee** [comment]
Hi, it seems like the issue list in the roadmap is not up-to-date then. Is there any part I can start contributing to? Thanks!

**Comment by nicolodavis** [comment]
Ah, sorry about that!  Will update the roadmap.

If you're interested in contributing to the Lobby, the main thing that needs to be done is migrate it to Svelte (similar to the Debug Panel [here](https://github.com/nicolodavis/boardgame.io/tree/master/src/client/debug)).  Is that something that you'd be interested in?

The other area of focus is bringing bots to multiplayer games.  See [here](https://github.com/nicolodavis/boardgame.io/issues/383#issuecomment-537317016) for details.

**Comment by EunPyoLee** [comment]
Cool. Thanks for links, I'll check them out and find a place where I can contribute to.

**Pull request closed without merging**
