### PR TITLE
fix(core): Don’t error if turn.order.next returns undefined

### PR DESCRIPTION
**Pull request by delucis**
Fixes a bug raised by @flamecoals in #605 where an error is logged if `turn.order.next` returns undefined, which is permitted as a way of ending the phase.

I’ve also amended the turn order interface to indicate that `next` can return undefined.

### CODE REVIEW

**Comment by nicolodavis** [comment]
Perhaps we should change the interface (in the future) to return a constant END_PHASE to make it more obvious.

**Comment by jasonharrison** [comment]
I ran into this on v0.39.6 (where the changelog https://github.com/nicolodavis/boardgame.io/blob/master/docs/documentation/CHANGELOG.md says this was fixed)

It looks like @delucis 's commit was reverted in https://github.com/nicolodavis/boardgame.io/commit/eb1e06070eabe7d2e723b3f35fd553100183621a#diff-ffe51a82f97e27f74a79b6b8382009e3L292

Was this accidental?

**Comment by nicolodavis** [comment]
Ah, that looks like a bad merge.

**Comment by nicolodavis** [comment]
Fixed and released in 0.39.7.

**Pull request merged**
