### PR TITLE
Add SQL connector

### PR DESCRIPTION
**Pull request by jasonharrison**
#### Checklist

* [X] Use a separate branch in your local repo (not `master`).
* [X] Test coverage is 100% (or you have a story for why it's ok).

### CODE REVIEW

**Comment by nicolodavis** [comment]
How does this compare with #226?

**Comment by jasonharrison** [comment]
@nicolodavis Hi, sorry for the delay in getting back to you.  I was not aware that PR #226 existed at the time I opened my own PR.

PR #226 looks quite old and has multiple files that are all pretty similar (mysql.js, sqlite.js, etc). 

My PR is one single sql.js that accepts parameters and passes them on to Sequelize.  It should behave the same regardless of whether it is using the SQLite/MySQL/PostgreSQL/etc dialects.  It defaults to an in-memory SQLite database, and I added sequelize/SQLite to dev dependencies so tests pass.

**Comment by nicolodavis** [comment]
Couple of comments:

1. I tried to add the SQL adapter to the examples (passing no arguments to it) and it didn't seem to work.  Any idea what could be going on? Specifically, try the "Authenticated Example".

2. Can you merge `master` in?

**Comment by jasonharrison** [comment]
I tried to run the react-web example and I am running into tons of dependency errors.  I did `npm install` then `npm run dev:client` and it seems like I just have to install dependency after dependency...

image

So I couldn't try using SQL in the example. 

This being said, sql.test.js passes, so I don't understand why it didn't work for you.  

Are you able to share the exact code you tried to run?  Also, do you know how I could fix my dependency problem?

**Comment by jasonharrison** [comment]
@nicolodavis When you get some free time, can you share your code?

**Comment by nicolodavis** [comment]
```
diff --git a/examples/react-web/server.js b/examples/react-web/server.js
index a9ba2ef..2c2527f 100644
--- a/examples/react-web/server.js
+++ b/examples/react-web/server.js
@@ -6,12 +6,12 @@
  * https://opensource.org/licenses/MIT.
  */

-import { Server } from 'boardgame.io/server';
+import { Server, SQL } from 'boardgame.io/server';
 import TicTacToe from './src/tic-tac-toe/game';
 import Chess from './src/chess/game';
 
 const PORT = process.env.PORT || 8000;
-const server = Server({ games: [TicTacToe, Chess] });
+const server = Server({ games: [TicTacToe, Chess], db: new SQL() });
 server.run(PORT, () => {
   console.log(`Serving at: http://localhost:${PORT}/`);
 });
```

**Comment by nicolodavis** [comment]
Also looks like you have a bad merge.

I don't see the changes from https://github.com/nicolodavis/boardgame.io/pull/374/commits/118a170aa439b25f72f57b512ee2549020aaf55e anymore and there are a lot more diffs in the PR than you originally intended I think.

**Comment by nicolodavis** [comment]
Almost ready to be merged!

Can we get rid of this error that I see on the terminal:
```
[dev:server] (node:8726) UnhandledPromiseRejectionWarning: SequelizeUniqueConstraintError: Validation error
[dev:server]     at Query.formatError (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/lib/di
alects/sqlite/query.js:417:16)
[dev:server]     at Statement.afterExecute (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/l
ib/dialects/sqlite/query.js:119:32)
[dev:server]     at Statement.replacement (/home/nicolodavis/Desktop/boardgame.io/node_modules/sqlite3/lib/
trace.js:19:31)
[dev:server] From previous event:
[dev:server]     at executeSql (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/lib/dialects/
sqlite/query.js:107:21)
[dev:server]     at Database.database.serialize (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequel
ize/lib/dialects/sqlite/query.js:297:18)
[dev:server]     at resolve (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/lib/dialects/sql
ite/query.js:102:21)
[dev:server] From previous event:
[dev:server]     at Query.run (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/lib/dialects/s
qlite/query.js:100:12)
[dev:server]     at Promise.try.then.connection (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequel
ize/lib/sequelize.js:558:20)
[dev:server] From previous event:
[dev:server]     at Promise.resolve.retryParameters (/home/nicolodavis/Desktop/boardgame.io/node_modules/se
quelize/lib/sequelize.js:555:8)
[dev:server]     at /home/nicolodavis/Desktop/boardgame.io/node_modules/retry-as-promised/index.js:39:21
[dev:server]     at retryAsPromised (/home/nicolodavis/Desktop/boardgame.io/node_modules/retry-as-promised/
index.js:29:10)
[dev:server]     at Sequelize.query (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/lib/sequ
elize.js:454:28)
[dev:server]     at QueryInterface.insert (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/li
b/query-interface.js:901:27)
[dev:server]     at Promise.try.then.then.then (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequeli
ze/lib/model.js:3685:53)
[dev:server]     at runCallback (timers.js:693:18)
[dev:server]     at tryOnImmediate (timers.js:664:5)
[dev:server]     at processImmediate (timers.js:646:5)
[dev:server] From previous event:
[dev:server]     at model.save (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/lib/model.js:
3661:8)
[dev:server]     at Function.create (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/lib/mode
l.js:2023:8)
[dev:server]     at SQL.create (/home/nicolodavis/Desktop/boardgame.io/src/server/db/sql.js:60:31)
[dev:server]     at tryCatch (/home/nicolodavis/Desktop/boardgame.io/node_modules/@babel/polyfill/node_modu
les/regenerator-runtime/runtime.js:62:40)
[dev:server]     at Generator.invoke [as _invoke] (/home/nicolodavis/Desktop/boardgame.io/node_modules/@bab
el/polyfill/node_modules/regenerator-runtime/runtime.js:288:22)
[dev:server]     at Generator.prototype.(anonymous function) [as next] (/home/nicolodavis/Desktop/boardgame
.io/node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js:114:21)
[dev:server]     at asyncGeneratorStep (/home/nicolodavis/Desktop/boardgame.io/src/server/db/sql.js:20:103)
[dev:server]     at _next (/home/nicolodavis/Desktop/boardgame.io/src/server/db/sql.js:22:194)
[dev:server] (node:8726) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originat
ed either by throwing inside of an async function without a catch block, or by rejecting a promise which wa
s not handled with .catch(). (rejection id: 1)
[dev:server] (node:8726) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the
future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit cod
e.
```

I get this by just running `npm start` and then going to either the Authenticated example under Tic-Tac-Toe or the Multiplayer example under Chess.

**Comment by nicolodavis** [comment]
Still getting the following error:

```
[dev:server] (node:7605) UnhandledPromiseRejectionWarning: SequelizeUniqueConstraintError: Validation error                                                                                                                                               
  3 [dev:server]     at Query.formatError (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/lib/di                                                                                                                                               
  4 alects/sqlite/query.js:426:16)                                                                                                                                                                                                                            
  5 [dev:server]     at Query._handleQueryResponse (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequeli                                                                                                                                               
  6 ze/lib/dialects/sqlite/query.js:77:18)                                                                                                                                                                                                                    
  7 [dev:server]     at Statement.afterExecute (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/l                                                                                                                                               
  8 ib/dialects/sqlite/query.js:260:31)                                                                                                                                                                                                                       
  9 [dev:server]     at Statement.replacement (/home/nicolodavis/Desktop/boardgame.io/node_modules/sqlite3/lib/                                                                                                                                               
 10 trace.js:19:31)                                                                                                                                                                                                                                           
 11 [dev:server] From previous event:                                                                                                                                                                                                                         
 12 [dev:server]     at executeSql (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/lib/dialects/                                                                                                                                               
 13 sqlite/query.js:253:19)                                                                                                                                                                                                                                   
 14 [dev:server]     at Database.conn.serialize (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/                                                                                                                                               
 15 lib/dialects/sqlite/query.js:308:16)                                                                                                                                                                                                                      
 16 [dev:server]     at resolve (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/lib/dialects/sql                                                                                                                                               
 17 ite/query.js:248:12)                                                                                                                                                                                                                                      
 18 [dev:server] From previous event:                                                                                                                                                                                                                         
 19 [dev:server]     at Query.run (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/lib/dialects/s                                                                                                                                               
 20 qlite/query.js:246:12)                                                                                                                                                                                                                                    
 21 [dev:server]     at Promise.try.then.connection (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequel                                                                                                                                               
 22 ize/lib/sequelize.js:574:22)                                                                                                                                                                                                                              
 23 [dev:server] From previous event:                                                                                                                                                                                                                         
 24 [dev:server]     at Promise.resolve.retryParameters (/home/nicolodavis/Desktop/boardgame.io/node_modules/se                                                                                                                                               
 25 quelize/lib/sequelize.js:571:10)                                                                                                                                                                                                                          
 26 [dev:server]     at /home/nicolodavis/Desktop/boardgame.io/node_modules/retry-as-promised/index.js:70:21                                                                                                                                                  
 27 [dev:server]     at new Promise (<anonymous>)                                                                                                                                                                                                             
 28 [dev:server]     at retryAsPromised (/home/nicolodavis/Desktop/boardgame.io/node_modules/retry-as-promised/                                                                                                                                               
 29 index.js:60:10)                                                                                                                                                                                                                                           
 30 [dev:server]     at Promise.try (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/lib/sequeliz                                                                                                                                               
 31 e.js:551:30)                                                                                                                                                                                                                                              
 32 [dev:server] From previous event:                                                                                                                                                                                                                         
 33 [dev:server]     at Sequelize.query (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/lib/sequ                                                                                                                                               
 34 elize.js:508:23)                                                                                                                                                                                                                                          
 35 [dev:server]     at QueryInterface.insert (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/li                                                                                                                                               
 36 b/query-interface.js:880:27)                                                                                                                                                                                                                              
 37 [dev:server]     at Promise.try.then.then.then (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequeli                                                                                                                                               
 38 ze/lib/model.js:3798:53)                                                                                                                                                                                                                                  
 39 [dev:server]     at runCallback (timers.js:693:18)                                                                                                                                                                                                        
 40 [dev:server]     at tryOnImmediate (timers.js:664:5)                                                                                                                                                                                                      
 41 [dev:server]     at processImmediate (timers.js:646:5)                                                                                                                                                                                                    
 42 [dev:server] From previous event:                                                                                                                                                                                                                         
 43 [dev:server]     at model.save (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/lib/model.js:                                                                                                                                               
 44 3774:8)                                                                                                                                                                                                                                                   
 45 [dev:server]     at Function.create (/home/nicolodavis/Desktop/boardgame.io/node_modules/sequelize/lib/mode                                                                                                                                               
 46 l.js:2202:8)                                                                                                                                                                                                                                              
 47 [dev:server]     at SQL.create (/home/nicolodavis/Desktop/boardgame.io/src/server/db/sql.js:60:31)                                                                                                                                                        
 48 [dev:server]     at tryCatch (/home/nicolodavis/Desktop/boardgame.io/node_modules/@babel/polyfill/node_modu                                                                                                                                               
 49 les/regenerator-runtime/runtime.js:62:40)                                                                                                                                                                                                                 
 50 [dev:server]     at Generator.invoke [as _invoke] (/home/nicolodavis/Desktop/boardgame.io/node_modules/@bab                                                                                                                                               
 51 el/polyfill/node_modules/regenerator-runtime/runtime.js:288:22)                                                                                                                                                                                           
 52 [dev:server]     at Generator.prototype.(anonymous function) [as next] (/home/nicolodavis/Desktop/boardgame                                                                                                                                               
 53 .io/node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js:114:21)                                                                                                                                                                      
 54 [dev:server]     at asyncGeneratorStep (/home/nicolodavis/Desktop/boardgame.io/src/server/db/sql.js:16:103)                                                                                                                                               
 55 [dev:server]     at _next (/home/nicolodavis/Desktop/boardgame.io/src/server/db/sql.js:18:194)                                                                                                                                                            
 56 [dev:server] (node:7605) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originat                                                                                                                                               
 57 ed either by throwing inside of an async function without a catch block, or by rejecting a promise which wa                                                                                                                                               
 58 s not handled with .catch(). (rejection id: 1)                                                                                                                                                                                                            
 59 [dev:server] (node:7605) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the                                                                                                                                                
 60 future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit cod                                                                                                                                               
 61 e.                          
```

I just ran `npm start` and clicked on "Multiplayer" under Chess, which hangs on "Connecting...".

![Screenshot from 2019-03-26 22-17-28](https://user-images.githubusercontent.com/236078/55004400-27932200-5015-11e9-8f11-ba4634b9a6dc.png)

**Comment by jasonharrison** [comment]
This is very strange.  It seems to work for me:

F9E3C3D8-BA75-42C5-B132-4255F0E18FCC

I will try to figure out what's going on tonight (and maybe @flamecoals can help).

Sorry about the problems with this PR Nicolo.  I'm happy you're carefully testing things and caught them.

**Comment by jasonharrison** [comment]
Never mind, I was able to reproduce but it took a few tries.  I am wondering this is an async race condition where we are saving game data but then try to retrieve it before it's saved.  I'll try to figure it out tonight.

**Comment by nicolodavis** [comment]
> Sorry about the problems with this PR Nicolo. I'm happy you're carefully testing things and caught them.

No worries! Take your time with it. We'll collectively make sure that it's robust before we get it in.

**Comment by jasonharrison** [comment]
@flamecoals and I worked to fix the various issues with the SQL connector.  

BGIO's API is far more friendly for a noSQL database; this PR would store everything as a blob in a single column.

The current problem with the SQL connector is the lack of using a transaction.  We encountered problems where it seemed like we were trying to read and set the state at the same time in a non-atomic operation, which led to a race condition.

After spending hours working on this PR and encountering issue after issue, @flamecoals and I decided that MongoDB is a better fit for our use case.  

@nicolodavis, would you like me to close this PR?

**Comment by nicolodavis** [comment]
You can leave it open for now. I'll take a look and see if I can salvage something from it. I'll close it later.

Thanks for looking into this!

**Comment by nicolodavis** [comment]
Closing this now that we have a Postgres connector: https://github.com/janKir/bgio-postgres

**Pull request closed without merging**
