### PR TITLE
Fix build and test issues

### PR DESCRIPTION
**Pull request by pardahlman**
I'm trying to build boardgame.io on my Macbook, but run into a few problems.

From the root of the directory

```
git clean -xdf
yarn
yarn test
```

First issue is that two test files (`events.test.js` and `master.test.js`) are not formatted according to the lint rules. The test run exits before any tests is even attempted to be run 🤔 .

Next issue seems to be with the `firebase-app` dependency. When running the tests, I get

```
  ● construction

    TypeError: instance.registerVersion is not a function

      38 |       this.client = require('firebase-admin');
      39 |     } else {
    > 40 |       this.client = require('firebase');
         |                     ^
      41 |     }
      42 | 
      43 |     this.engine = engine === ENGINE_RTDB ? engine : ENGINE_FIRESTORE;

      at registerDatabase (node_modules/@firebase/database/index.node.ts:136:12)
      at Object.<anonymous> (node_modules/@firebase/database/index.node.ts:151:3)
      at Object.<anonymous> (node_modules/firebase/dist/index.node.cjs.js:7:1)
      at new Firebase (src/server/db/firebase.js:40:21)
      at Object.<anonymous> (src/server/db/firebase.test.js:43:14)
```

This looks like [the same issue as described here](https://github.com/firebase/firebase-tools/issues/1989), and upgrading to latest version solved the issue.

Now, `yarn test` works. Next, I had a look at `yarn test:watch`. The process exists prematurely with the following output

```
> yarn test:watch
yarn run v1.19.1
$ cross-env NODE_ENV=test jest --watch
Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
This issue was solved by upgrading jest to `25.1.0`, and subsequently update `ts-jest` to get rid of the warning that it was not tested against the new version of jest.

The test suit goes green, but has a few warnings that probably should be looked at:

```
PASS  src/server/db/mongo.test.js
(node:61200) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'moves' of undefined
(node:61200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:61200) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
And

```
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --runInBand --detectOpenHandles to find leaks.
```
I haven't looked at this issues 🤷‍♂

### CODE REVIEW

**Comment by pardahlman** [comment]
Um... right, `yarn.lock` is ignored and `package-lock.json` is used. I'll npm and update the PR 👍

**Comment by pardahlman** [comment]
"Job 1" failes and "Job 2" succeeds -- it is not transparent to me what the differences are 😬

**Comment by pardahlman** [comment]
Got "Job 1" to pass the linting by upgrading prettier 👍 .

There is a warning in the `test:coverage` stage

```
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
```

I believe I got rid of them by upgrading `@babel/preset-env`. Now the tests fail on

```
FAIL src/client/react.ssr.test.js
  ● Test suite failed to run

    ReferenceError: expect is not defined

      at Object.<anonymous> (node_modules/@testing-library/jest-dom/dist/extend-expect.js:7:1)
      at Object.<anonymous> (node_modules/@testing-library/jest-dom/extend-expect.js:2:1)
```

**Comment by pardahlman** [comment]
Looks like there is still an issue with `extend-expect` - looks similar to [this issue](https://github.com/testing-library/jest-dom/issues/122) and could perhaps be related to the fact that`extend-expect` was imported both in a test explicitly (`debug.test.js`) as well as in the `setupFilesAfterEnv` (which doesn't seem to be what is [recommended in the documentation](https://github.com/testing-library/jest-dom#usage)). I was not able to fix this.

I created #567 to verify that all this work wasn't in vain -- to me it looks like the CI system is failing on master.

**Comment by nicolodavis** [comment]
The CI system is not failing on master.

Your PR #567 fails due to a lint error (file with an empty line): https://semaphoreci.com/nicolodavis/boardgame-io/branches/pull-request-567/builds/1

I think what you're observing is that the build breaks when certain dependencies are updated (things  work just fine on my workstation as well as on the CI currently).

Perhaps we should update the deps one by one (`prettier`, `@babel/preset-env` etc.)?

**Comment by pardahlman** [comment]
Sounds like a plan, on the other hand some dependencies goes hand by hand (like `ts-test` warns if a newer version of  `jest` is used).

I still think that it is strange that I got linting errors on master on a completely clean build. Do you know what version of node the CI-system runs?

**Comment by nicolodavis** [comment]
Node 10.10

**Comment by nicolodavis** [comment]
@pardahlman Are there any issues from this PR that remain (looks like most were addressed in separate changes)?

**Comment by delucis** [comment]
Closing due to lack of activity — please feel free to reopen.

**Pull request closed without merging**
