### PR TITLE
Missing dependencies for UI package

### PR DESCRIPTION
**Pull request by flamecoals**
These two dependencies were marked as devDependency, which broke [freeboardgame.org](http://freeboardgame.org) tests. Adding them as regular deendency fixed our issues.
See errors:
```
 FAIL  src/Home/Home.test.tsx                                                                                                                                                          
  ● Test suite failed to run                                                                                                                                                           
                                                                                                                                                                                       
    Cannot find module '@tweenjs/tween.js' from 'ui.js'                                                                                                                                
                                                                                                                                                                                       
    However, Jest was able to find:                                                                                                                                                    
        './checkerboard.test.tsx'                                                                                                                                                      
        './checkerboard.tsx'                                                                                                                                                           
                                                                                                                                                                                       
    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['ts', 'tsx', 'js'].                                          
                                                                                                                                                                                       
    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string
```

```
FAIL  src/App/Game/Game.test.tsx                                                                                                                                                      
  ● Test suite failed to run                                                                                                                                                           
                                                                                                                                                                                       
    Cannot find module 'three' from 'ui.js'                                                                                                                                            
                                                                                                                                                                                       
    However, Jest was able to find:                                                                                                                                                    
        './checkerboard.test.tsx'                                                                                                                                                      
        './checkerboard.tsx'                                                                                                                                                           
                                                                                                                                                                                       
    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['ts', 'tsx', 'js'].                                          
                                                                                                                                                                                       
    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string   
```

#### Checklist

* [x] Use a separate branch in your local repo (not `master`).
* [x] Test coverage is 100% (or you have a story for why it's ok).

### CODE REVIEW

**Comment by nicolodavis** [comment]
Given that the 3D stuff is still experimental, I'm leaning toward just requiring users to install three separately (just like React isn't a dependency).

We can move tween to the deps though.

**Comment by flamecoals** [comment]
> Given that the 3D stuff is still experimental, I'm leaning toward just requiring users to install three separately (just like React isn't a dependency).
> 
> We can move tween to the deps though.

I am not using any 3D stuff in my app though, and it still require three installed. If we do not add three as a dep, the UI import will break.

**Comment by nicolodavis** [comment]
Then we should probably change the `import` to a `require` similar to how we handle Firebase or Mongo (we don't pull in those deps automatically).

**Comment by flamecoals** [comment]
Agreed :). I can try doing that later.

**Comment by nicolodavis** [comment]
BTW, the integration test is broken due to https://github.com/webpack-contrib/terser-webpack-plugin/issues/66.

**Comment by flamecoals** [comment]
OK, I changed to require() and removed it from deps (added it back to dev deps...). This should work now :)

**Comment by flamecoals** [comment]
Gosh, I still get the error using require (only when running webpack, not the tests):
```
ERROR in ./node_modules/flamecoals-boardgame.io/dist/ui.js
Module not found: Error: Can't resolve 'three' in '/home/felizardow/playground/FreeBoardGame.org/node_modules/flamecoals-boardgame.io/dist'
 @ ./node_modules/flamecoals-boardgame.io/dist/ui.js 300:20-36 868:20-36 1098:20-36
 @ ./node_modules/flamecoals-boardgame.io/ui.js
 @ ./src/games/chess/board.tsx
 @ ./src/games/index.tsx
 @ ./src/App/Game/GameInfo.tsx
 @ ./src/App/App.tsx
 @ ./src/app.tsx
```

Line 868 is:
```
      _this.originalY = props.thickness / 2 - 0.0001;
      _this.three = require('three');
      var geometry = new _this.three.BoxGeometry(props.width, props.thickness, props.height);
```

**Comment by flamecoals** [comment]
@nicolodavis any idea of solution for this issue? It seems like webpack is calling the constructor of the 3D UI even though I only use the 2D UI...

**Comment by nicolodavis** [comment]
Hmm, hard to tell without looking at your specific webpack config.  Are you using an option that is causing it to try to resolve `require` statements as well?

**Comment by flamecoals** [comment]
I am using the latest webpack and it does try to resolve requires. Thats probably why indeed. I'm going to close this

**Comment by nicolodavis** [comment]
I see. Do you have a workaround?

**Comment by flamecoals** [comment]
No, I just installed it. The other solution would be to separate the 3d and
the 2d modules, but I think that's just too much work.

**Pull request closed without merging**
