### PR TITLE
Fixes #713

### LINKED ISSUE #713: server sync problem
Seems that there is problem with reconnection. Im running game with local server and sometimes completly randomly without any error runs only on current client, server has no info no move is played. Only way is to restart the server (client restart ends up with 'connecting...' loader in place of client) it is like 10% of cases. Game is pretty complex so i will need to create small repo for reproduction, but seems that multiplayer is broken.  Will provide more detail once i will track down way of data from client to server ( debuggin this library is not that simple thing) but smells like problem with socket disconnection and then reconnection.

### PR DESCRIPTION
**Pull request by flamecoals**
Fixes #713

#### Checklist

* [x] Use a separate branch in your local repo (not `master`).
* [x] Test coverage is 100% (or you have a story for why it's ok).

### CODE REVIEW

**Comment by jabza** [comment]
Possible to get this released soon? cheers :)

**Comment by nicolodavis** [comment]
Thanks @flamecoals!

Does this fix the issue for you (I'm guessing you use an internal fork and aren't blocked by a release from us)?

I think there might still be a possibility of a desync if:
- The internet connection is slow, but the socket itself hasn't disconnected.

I think the eventual solution should probably be something like:
- The server just sends a sync response back whenever it receives a stale response from the client. Right now it just [rejects](https://github.com/nicolodavis/boardgame.io/blob/master/src/master/master.ts#L272) the response without any further action.

**Comment by flamecoals** [comment]
It fixed for the case that the internet drops completely, I agree with you that it wont fix for the case of it being slow. It is quite bit hard to simulate these scenarios though, because Chrome does not apply the network settings to Websockets.

We got rid of our internal fork in order to reduce complexity, so we are still waiting for release, it would be great if it could be released :)

**Comment by nicolodavis** [comment]
> Chrome does not apply the network settings to Websockets.

Yeah, I find this quite annoying as well!

> We got rid of our internal fork in order to reduce complexity, so we are still waiting for release, it would be great if it could be released :)

This is released as `0.39.13`.

**Comment by delucis** [comment]
If we implement something like #723, issuing a `sync` in response to stale state would conflict with that model, but if the server can reliably fix errors like this, that would be a better experience. Perhaps #723 should consider if there any other situations like this that can “self heal”?

**Comment by flamecoals** [comment]
Thanks for the release!

**Pull request merged**
