### PR TITLE
Update tutorial w/ npx script

### PR DESCRIPTION
**Pull request by mgmarlow**
#### Checklist

* [x] Use a separate branch in your local repo (not `master`).
* [x] Test coverage is 100% (or you have a story for why it's ok).

### CODE REVIEW

**Comment by nicolodavis** [comment]
Hey @mgmarlow thanks for the PR!

`npx` is great, but since this is the very first article that users are likely to encounter in the docs, I'd prefer to keep the number of concepts low.

Most people are familiar with `npm`, but may not know what `npx` is.

Is there anything else on the docs that you think could use improvement?

**Comment by mgmarlow** [comment]
@nicolodavis Thanks for the quick reply on this one, this is just something that popped out at me after running through the create-react-app docs. Haven't had any other issues running through the rest of the docs.

**Comment by nicolodavis** [comment]
That's good. People have often had trouble with the multiplayer section. Did everything work as intended for you?

**Comment by mgmarlow** [comment]
Haven't tried implementing the multiplayer section, so I can't speak towards it.

**Pull request closed without merging**
