### PR TITLE
fix: Fix join/leave a room when playerID is 0

### LINKED ISSUE #420: Player.id=0 cannot leave game
When the first player (player.id=0) tries to use the /leave endpoint, they get a 403 error because of the following check in the /server/api.js:

`if (!playerID) {
      ctx.throw(403, 'playerID is required');
    }`

The check should instead be

`if (typeof playerID === 'undefined') {`

This should also be changed for the /join endpoint.

### PR DESCRIPTION
**Pull request by billyvg**
Fixes joining/leaving a room for playerID = 0.

Closes #420

#### Checklist

* [x] Use a separate branch in your local repo (not `master`).
* [ ] Test coverage is 100% (or you have a story for why it's ok).

### CODE REVIEW

**Comment by flamecoals** [comment]
+1 for merge, this thing broke FreeBoardGame.org when we upgraded to HEAD

**Comment by flamecoals** [comment]
@nicolodavis Can we please merge this quickly? This is breaking the lobby for everybody. 

#425 another duplicate PR fixing the same issue

**Comment by flamecoals** [comment]
It seems like @jasonharrison forgot to push a commit with that before merging the PR.
We should probably add some regression test to avoid this happening agian

**Comment by nicolodavis** [comment]
Sorry about the delay.  I'm still out on vacation.  Will be back next week.

**Comment by nicolodavis** [comment]
I've merged it in.  Will make a release once I'm back.

**Pull request merged**
